# This file pins all the gz-* libraries to version consistents to the Jetty release, to ensure
# that a Jetty libraries does not silently depend on a newer version of another gz-* library when released
# See https://github.com/conda-forge/gz-sim-feedstock/issues/102#issuecomment-3345944591
# Based on the info from https://github.com/gazebo-tooling/gazebodistro/blob/680c7f921d7c05ea89742cf9f6e3c6e669ada291/collection-jetty.yaml
# The package being built is commented out to avoid crashes in conda-smithy rerender

libgz_cmake:
  - 5
libgz_common:
  - 7
libgz_fuel_tools:
  - 11
libgz_sim:
  - 10
libgz_gui:
  - 10
libgz_launch:
  - 9
#libgz_math:
#  - 9
libgz_msgs:
  - 12
libgz_physics:
  - 9
libgz_plugin:
  - 4
libgz_rendering:
  - 10
libgz_sensors:
  - 10
libgz_tools:
  - 2
libgz_transport:
  - 15
libgz_utils:
  - 4
libsdformat:
  - 16
