context:
  version: "9.0.0"
  major_version: "9"
  component_name: "math"
  repo_name: "gz-math"
  name: "gz-math"
  cxx_name: "libgz-math"
  python_name: "gz-math-python"

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: "https://github.com/gazebosim/${{ repo_name }}/archive/${{ repo_name }}${{ major_version }}_${{ version }}.tar.gz"
    sha256: "e1eacfc2bf6b875ec270b6323cfaa8dfe043c9aaff9ceb8f87ff46e1cde9474a"

build:
  number: 0

outputs:
  - package:
      name: ${{ cxx_name }}
    build:
      script:
        - if: unix
          then: build_cxx.sh
        - if: win
          then: bld_cxx.bat
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - pkg-config
        - ninja
        # INTEGRATION_ExamplesBuild_TEST requires the use of Make
        - if: not win
          then:
            - make
      host:
        - libgz-cmake
        - libgz-utils
        - eigen
      run:
        - eigen
      run_exports:
        - ${{ pin_subpackage(cxx_name, upper_bound='x') }}

    tests:
      - package_contents:
          include:
            - "gz/${{ component_name }}/gz/${{ component_name }}.hh"
          lib:
            - ${{ name }}
      - script:
          - cmake-package-check gz-math
        requirements:
          run:
            - cmake-package-check
            - ${{ compiler('c') }}
            - ${{ compiler('cxx') }}
  - package:
      name: ${{ python_name }}
    build:
      script:
        - if: unix
          then: build_py.sh
        - if: win
          then: bld_py.bat
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - pkg-config
        - ninja
        - if: build_platform != target_platform
          then:
            - cross-python_${{ target_platform }}
            - python
            - pybind11
            - pybind11-abi
            - pytest
      host:
        - ${{ pin_subpackage(cxx_name, exact=true) }}
        - python
        - pybind11
        - pybind11-abi
        - pytest
      run:
        - ${{ pin_subpackage(cxx_name, exact=true) }}
        - python

    tests:
      - python:
          imports:
            - gz.math

  - package:
      name: ${{ name }}
    requirements:
      run:
        - ${{ pin_subpackage(cxx_name, exact=true) }}
        - ${{ pin_subpackage(python_name, upper_bound='x.x.x') }}
      run_exports:
        - ${{ pin_subpackage(cxx_name, upper_bound='x') }}
    tests:
      - script:
          - cmake-package-check gz-math
        requirements:
          run:
            - cmake-package-check
            - ${{ compiler('c') }}
            - ${{ compiler('cxx') }}
      - python:
          imports:
            - gz.math

about:
  homepage: https://github.com/gazebosim/gz-math
  repository: https://github.com/gazebosim/gz-math
  license: "Apache-2.0"
  license_file: "LICENSE"
  summary: "General purpose math library for robot applications."

extra:
  recipe-maintainers:
    - wolfv
    - traversaro
    - j-rivero
